[package]
name = "instagram-telegram-bot"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
anyhow = "1.0.95"
redis = { version = "0.27.6", features = ["tokio-comp", "connection-manager"] }
reqwest = { version = "0.11.27", features = ["json", "socks"] }
# Serialization
serde = { version = "1.0.216", features = ["derive"] }
serde_json = "1.0.134"
shuttle-runtime = "0.49.0"
teloxide = { version = "0.13.0", features = ["macros", "throttle"] }
tokio = { version = "1.42.0", features = ["full"] }
# Logging and tracing
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }

# URL parsing and validation
url = "2.5.2"

# Hashing for file names
sha2 = "0.10"

# Time handling
chrono = { version = "0.4.39", features = ["serde"] }

# Async traits
async-trait = "0.1.83"
thiserror = "2.0.9"
