name: Test & Coverage

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always
  # MIN_COVERAGE: 80 # TODO: Add --fail-under
  REDIS_HOST: redis
  SRH_HOST: srh

jobs:
  test:
    timeout-minutes: 30
    name: Test & Coverage
    runs-on: ubuntu-latest
    container:
      image: xd009642/tarpaulin:0.31.4
      options: --security-opt seccomp=unconfined
      env:
        REDIS_HOST: redis
        SRH_HOST: srh

    services:
      redis:
        image: redis/redis-stack-server:6.2.6-v6
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      srh:
        image: hiett/serverless-redis-http:latest
        env:
          SRH_MODE: standalone
          SRH_REDIS_URL: redis://redis:6379
        ports:
          - 8079:80

    steps:
      - uses: actions/checkout@v4

      - name: Install jq
        run: |
          apt-get update && apt-get install -y jq

      - name: Create Turso Test Database
        id: create_db
        run: |
          echo "Creating database: ${{ github.ref_name }}-${{ github.run_id }}"

          # Create database
          CREATE_RESPONSE=$(curl -L -X POST "https://api.turso.tech/v1/organizations/${{ secrets.TURSO_ORGANIZATION_NAME }}/databases" \
            -H "Authorization: Bearer ${{ secrets.TURSO_API_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{
              "name": "${{ github.ref_name }}-${{ github.run_id }}",
              "group": "default",
              "seed": {
                "type": "database",
                "name": "${{ secrets.TURSO_EXISTING_DATABASE_NAME }}"
              }
            }')

          # Check for errors in creation response
          ERROR=$(echo "$CREATE_RESPONSE" | jq -r '.error')
          if [ "$ERROR" != "null" ]; then
            echo "Failed to create database: $ERROR"
            echo "Full response: $CREATE_RESPONSE"
            exit 1
          fi

          echo "Database creation successful"

      - name: Get Database Token
        run: |
          set +x  # Disable command echo

          # Create database token using Platform API
          token=$(curl -L -X POST \
            "https://api.turso.tech/v1/organizations/${{ secrets.TURSO_ORGANIZATION_NAME }}/databases/${{ github.ref_name }}-${{ github.run_id }}/auth/tokens?expiration=1h&authorization=full-access" \
            -H "Authorization: Bearer ${{ secrets.TURSO_API_TOKEN }}" \
            -H "Content-Type: application/json" \
            | jq -r '.jwt')

          # Verify we got a token
          if [ -z "$token" ]; then
            echo "Failed to get database token"
            exit 1
          fi

          echo "::add-mask::$token"
          echo "TURSO_TOKEN=$token" >> $GITHUB_ENV
          echo "TURSO_URL=libsql://${{ env.TURSO_HOSTNAME }}" >> $GITHUB_ENV

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            ~/.rustup/toolchains/ 
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-
            ${{ runner.os }}-cargo-

      - name: Run tests with coverage
        id: coverage
        env:
          TURSO_URL: ${{ env.TURSO_URL }}
          TURSO_TOKEN: ${{ env.TURSO_TOKEN }}
        run: |
          cargo tarpaulin --out xml
        # --fail-under $MIN_COVERAGE # TODO

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true

      - name: Cleanup Turso Database
        if: always()
        run: |
          response=$(
            curl -L -X DELETE \
              "https://api.turso.tech/v1/organizations/${{ secrets.TURSO_ORGANIZATION_NAME }}/databases/${{ github.ref_name }}-${{ github.run_id }}" \
              -H "Authorization: Bearer ${{ secrets.TURSO_API_TOKEN }}"
          )

          if [ $(echo "$response" | jq -r '.error') != "null" ]; then
            echo "Failed to delete database"
            exit 1
          fi

          echo "Database deleted successfully"
